module.exports = async function (context, req) {
    const userMessage = req.body && req.body.message;

    if (!userMessage) {
        context.res = {
            status: 400,
            body: { reply: "Error: Please provide a message." }
        };
        return;
    }

    const endpoint = process.env.Endpoint; // https://hackathongroup3-resource.services.ai.azure.com/api/projects/hackathongroup3
    const apiKey = process.env.API;
    const agentId = process.env.AIChatbot; // af77a774-aa5d-4dab-a688-799b9e80a80f

    try {
        const apiVersion = "2024-05-01-preview";

        // 1. Create thread and run your exact Foundry agent in one request
        const runRes = await fetch(`${endpoint}/openai/threads/runs?api-version=${apiVersion}`, {
            method: 'POST',
            headers: { 
                'api-key': apiKey, 
                'Content-Type': 'application/json' 
            },
            body: JSON.stringify({
                assistant_id: agentId,
                thread: {
                    messages: [
                        { role: "user", content: userMessage }
                    ]
                }
            })
        });

        const runData = await runRes.json();
        
        if (!runData.id || !runData.thread_id) {
            throw new Error(runData.error ? runData.error.message : "Failed to trigger the agent.");
        }

        const threadId = runData.thread_id;
        const runId = runData.id;

        // 2. Poll until the agent finishes processing your request
        let status = runData.status;
        let attempts = 0;
        
        while (status !== "completed" && attempts < 15) {
            await new Promise(resolve => setTimeout(resolve, 1000));
            attempts++;

            const statusRes = await fetch(`${endpoint}/openai/threads/${threadId}/runs/${runId}?api-version=${apiVersion}`, {
                method: 'GET',
                headers: { 'api-key': apiKey }
            });
            const statusData = await statusRes.json();
            status = statusData.status;

            if (status === "failed" || status === "cancelled" || status === "expired") {
                throw new Error("Agent execution stopped with status: " + status);
            }
        }

        if (status !== "completed") {
            throw new Error("Agent response timed out.");
        }

        // 3. Fetch the final messages from the thread generated by your agent
        const messagesRes = await fetch(`${endpoint}/openai/threads/${threadId}/messages?api-version=${apiVersion}`, {
            method: 'GET',
            headers: { 'api-key': apiKey }
        });
        const messagesData = await messagesRes.json();
        
        const assistantMessage = messagesData.data.find(m => m.role === "assistant");
        const replyText = assistantMessage ? assistantMessage.content[0].text.value : "No response generated by agent.";

        context.res = {
            body: { reply: replyText }
        };

    } catch (error) {
        context.res = {
            status: 500,
            body: { reply: "Agent Connection Error: " + error.message }
        };
    }
};
