module.exports = async function (context, req) {
    const userMessage = req.body.message;
    
    const endpoint = process.env.Endpoint; // https://.../api/projects/hackathongroup3
    const apiKey = process.env.API;
    const agentId = process.env.AIChatbot; // af77a774-aa5d-4dab-a688-799b9e80a80f

    try {
        // 1. Create a thread and run the specific Agent ID directly using Foundry Project API
        const response = await fetch(`${endpoint}/openai/threads/runs?api-version=2024-05-01-preview`, {
            method: 'POST',
            headers: { 
                'api-key': apiKey, 
                'Content-Type': 'application/json' 
            },
            body: JSON.stringify({
                assistant_id: agentId,
                thread: {
                    messages: [
                        { role: "user", content: userMessage }
                    ]
                }
            })
        });

        const runData = await response.json();
        
        if (!runData.id || !runData.thread_id) {
            throw new Error(runData.error ? runData.error.message : "Failed to trigger the AI agent.");
        }

        const threadId = runData.thread_id;
        const runId = runData.id;

        // 2. Poll until your Agent finishes processing (up to 15 seconds)
        let status = runData.status;
        let attempts = 0;
        
        while (status !== "completed" && attempts < 15) {
            await new Promise(resolve => setTimeout(resolve, 1000));
            attempts++;

            const statusRes = await fetch(`${endpoint}/openai/threads/${threadId}/runs/${runId}?api-version=2024-05-01-preview`, {
                method: 'GET',
                headers: { 'api-key': apiKey }
            });
            const statusData = await statusRes.json();
            status = statusData.status;

            if (status === "failed" || status === "cancelled" || status === "expired") {
                throw new Error("Agent execution stopped with status: " + status);
            }
        }

        if (status !== "completed") {
            throw new Error("Agent response timed out.");
        }

        // 3. Fetch the final output messages generated by your Agent
        const messagesRes = await fetch(`${endpoint}/openai/threads/${threadId}/messages?api-version=2024-05-01-preview`, {
            method: 'GET',
            headers: { 'api-key': apiKey }
        });
        const messagesData = await messagesRes.json();
        
        const assistantMessage = messagesData.data.find(m => m.role === "assistant");
        const replyText = assistantMessage ? assistantMessage.content[0].text.value : "No response generated by agent.";

        context.res = { body: { reply: replyText } };

    } catch (error) {
        context.res = { status: 500, body: { reply: "Agent Connection Error: " + error.message } };
    }
};
